export const PREVIOUS_MONTH = "PREVIOUS_MONTH";
export const NEXT_MONTH = "NEXT_MONTH";
export const ADD_NEW_REMINDER = "ADD_NEW_REMINDER";
export const UPDATE_REMINDER = "UPDATE_REMINDER";
export const REMOVE_REMINDER = "REMOVE_REMINDER";
